In [59]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [60]:
df1 = pd.read_csv('datasets/Briliant_diamonds/diamonds_dataset.csv')
df2 = pd.read_csv('datasets/Diamonds/diamonds.csv')

In [61]:
df1

,id,url,shape,price,carat,cut,color,clarity,report,type,date_fetched
0,10086429,https://www.brilliantearth.com//loose-diamonds...,Round,400,0.30,Very Good,J,SI2,GIA,natural,2020-11-29 12-26 PM
1,10016334,https://www.brilliantearth.com//loose-diamonds...,Emerald,400,0.31,Ideal,I,SI1,GIA,natural,2020-11-29 12-26 PM
2,9947216,https://www.brilliantearth.com//loose-diamonds...,Emerald,400,0.30,Ideal,I,VS2,GIA,natural,2020-11-29 12-26 PM
3,10083437,https://www.brilliantearth.com//loose-diamonds...,Round,400,0.30,Ideal,I,SI2,GIA,natural,2020-11-29 12-26 PM
4,9946136,https://www.brilliantearth.com//loose-diamonds...,Emerald,400,0.30,Ideal,I,SI1,GIA,natural,2020-11-29 12-26 PM
...,...,...,...,...,...,...,...,...,...,...,...
119302,10081678,https://www.brilliantearth.com//lab-diamonds-s...,Round,99040,5.71,Super Ideal,D,VVS2,GCAL,lab,2020-11-29 12-26 PM
119303,9521564,https://www.brilliantearth.com//lab-diamonds-s...,Cushion,107330,15.32,Very Good,G,SI2,IGI,lab,2020-11-29 12-26 PM
119304,9896730,https://www.brilliantearth.com//lab-diamonds-s...,Cushion,110110,10.05,Ideal,D,SI2,IGI,lab,2020-11-29 12-26 PM
119305,9756570,https://www.brilliantearth.com//lab-diamonds-s...,Oval,126030,10.33,Fair,D,VS2,IGI,lab,2020-11-29 12-26 PM
119306,9293400,https://www.brilliantearth.com//lab-diamonds-s...,Cushion,141710,10.25,Good,E,VS1,IGI,lab,2020-11-29 12-26 PM

In [62]:
df1 = df1.drop(columns=['url', 'date_fetched', 'id'])
#df1 = df1.drop(columns=['id'])

In [63]:
df1

          shape   price  carat          cut color clarity report     type
0         Round     400   0.30    Very Good     J     SI2    GIA  natural
1       Emerald     400   0.31        Ideal     I     SI1    GIA  natural
2       Emerald     400   0.30        Ideal     I     VS2    GIA  natural
3         Round     400   0.30        Ideal     I     SI2    GIA  natural
4       Emerald     400   0.30        Ideal     I     SI1    GIA  natural
...         ...     ...    ...          ...   ...     ...    ...      ...
119302    Round   99040   5.71  Super Ideal     D    VVS2   GCAL      lab
119303  Cushion  107330  15.32    Very Good     G     SI2    IGI      lab
119304  Cushion  110110  10.05        Ideal     D     SI2    IGI      lab
119305     Oval  126030  10.33         Fair     D     VS2    IGI      lab
119306  Cushion  141710  10.25         Good     E     VS1    IGI      lab

[119307 rows x 8 columns]

In [64]:
clarity_map = {
    'FL': 0,
    'IF': 0.125,
    'VVS1': 0.25,
    'VVS2': 0.5,
    'VS1': 0.625,
    'VS2': 0.75,
    'SI1': 0.875,
    'SI2': 1
}

df1['clarity'] = df1['clarity'].map(clarity_map)

In [65]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 119307 entries, 0 to 119306
Data columns (total 8 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   shape    119307 non-null  str
 1   price    119307 non-null  int64
 2   carat    119307 non-null  float64
 3   cut      119307 non-null  str
 4   color    119307 non-null  str
 5   clarity  119307 non-null  float64
 6   report   119307 non-null  str
 7   type     119307 non-null  str
dtypes: float64(2), int64(1), str(5)
memory usage: 9.9 MB

In [66]:
df1.to_csv('datasets/Briliant_diamonds/diamonds_dataset.csv', index=False)

In [67]:
df2 = df2.drop(columns=['Unnamed: 0'])

In [68]:
df2.to_csv('datasets/Diamonds/diamonds.csv', index=False)